# Imports

In [12]:
from glob import glob
import shutil
import os

# Create groups of 64 slices

In [5]:
in_path = 'C:/Users/User/Downloads/Liver/labels'
out_path = 'C:/Users/User/Downloads/Liver/dicom_groups/labels'

In [18]:
# glob --> creates the list of directories also handling Unix code
for patient in glob(in_path + '/*'):
    print(patient)

C:/Users/User/Downloads/Liver/labels\liver_0
C:/Users/User/Downloads/Liver/labels\liver_1
C:/Users/User/Downloads/Liver/labels\liver_2
C:/Users/User/Downloads/Liver/labels\liver_3
C:/Users/User/Downloads/Liver/labels\liver_4
C:/Users/User/Downloads/Liver/labels\liver_5
C:/Users/User/Downloads/Liver/labels\liver_6
C:/Users/User/Downloads/Liver/labels\liver_7
C:/Users/User/Downloads/Liver/labels\liver_8
C:/Users/User/Downloads/Liver/labels\liver_9


In [25]:
for patient in glob(in_path + '/*'):
    patient_name = os.path.basename(os.path.normpath(patient)) 
    number_folders = int(len(glob(patient+'/*'))/64) # number of folders required to group 64 for each patient

    for i in range(number_folders):
        output_path_name = os.path.join(out_path, patient_name + '_' + str(i))
        os.mkdir(output_path_name)
        for j, file in enumerate(glob(patient+'/*')):
            if j == 64:
                break
            shutil.move(file, output_path_name)

# 64 slices of images

In [26]:
in_path = 'C:/Users/User/Downloads/Liver/images'
out_path = 'C:/Users/User/Downloads/Liver/dicom_groups/images'

In [27]:
for patient in glob(in_path + '/*'):
    patient_name = os.path.basename(os.path.normpath(patient)) 
    number_folders = int(len(glob(patient+'/*'))/64) # number of folders required to group 64 for each patient

    for i in range(number_folders):
        output_path_name = os.path.join(out_path, patient_name + '_' + str(i))
        os.mkdir(output_path_name)
        for j, file in enumerate(glob(patient+'/*')):
            if j == 64:
                break
            shutil.move(file, output_path_name)

# Convert DICOM to NIfTI

In [29]:
import dicom2nifti

In [32]:
in_path_images = 'C:/Users/User/Downloads/Liver/dicom_groups/images/*'
in_path_labels = 'C:/Users/User/Downloads/Liver/dicom_groups/labels/*'

out_path_images = 'C:/Users/User/Downloads/Liver/nifit_files/images'
out_path_labels = 'C:/Users/User/Downloads/Liver/nifit_files/labels'

list_images = glob(in_path_images)
list_labels = glob(in_path_labels)

In [34]:
for patient in list_images:
    patient_name = os.path.basename(os.path.normpath(patient))
    dicom2nifti.dicom_series_to_nifti(patient, os.path.join(out_path_images, patient_name + '.nii.gz'))

In [35]:
for patient in list_labels:
    patient_name = os.path.basename(os.path.normpath(patient))
    dicom2nifti.dicom_series_to_nifti(patient, os.path.join(out_path_labels, patient_name + '.nii.gz'))

# Find empty

In [51]:
import nibabel as nib
import numpy as np

In [55]:
input_nifti_file_path = 'C:/Users/User/Downloads/Liver/nifit_files/labels/*'
list_nifti_labels = glob(input_nifti_file_path)

for patient in list_nifti_labels:
    nifti_file = nib.load(patient)
    fdata = nifti_file.get_fdata() # retrieves the image data as a NumPy array, here, 64 slides
    np_unique = np.unique(fdata) # Find the unique value in array 
    print(np_unique)
    if len(np_unique) == 1: # if only 0 in the array --> empty image
        print(patient)

[0. 1. 2.]
[0. 1. 2.]
[0.]
C:/Users/User/Downloads/Liver/nifit_files/labels\liver_2_0.nii.gz
[0.]
C:/Users/User/Downloads/Liver/nifit_files/labels\liver_2_1.nii.gz
[0.]
C:/Users/User/Downloads/Liver/nifit_files/labels\liver_2_2.nii.gz
[0.]
C:/Users/User/Downloads/Liver/nifit_files/labels\liver_2_3.nii.gz
[0.]
C:/Users/User/Downloads/Liver/nifit_files/labels\liver_2_4.nii.gz
[0. 1.]
[0. 1. 2.]
[0. 1. 2.]
[0.]
C:/Users/User/Downloads/Liver/nifit_files/labels\liver_3_0.nii.gz
[0.]
C:/Users/User/Downloads/Liver/nifit_files/labels\liver_3_1.nii.gz
[0.]
C:/Users/User/Downloads/Liver/nifit_files/labels\liver_3_2.nii.gz
[0.]
C:/Users/User/Downloads/Liver/nifit_files/labels\liver_3_3.nii.gz
[0. 1.]
[0. 1. 2.]
[0. 1.]
[0. 1.]
[0.]
C:/Users/User/Downloads/Liver/nifit_files/labels\liver_4_0.nii.gz
[0.]
C:/Users/User/Downloads/Liver/nifit_files/labels\liver_4_1.nii.gz
[0.]
C:/Users/User/Downloads/Liver/nifit_files/labels\liver_4_10.nii.gz
[0.]
C:/Users/User/Downloads/Liver/nifit_files/labels\liver_

In [56]:
input_nifti_file_path = 'C:/Users/User/Downloads/Liver/nifit_files/labels/*'
list_nifti_labels = glob(input_nifti_file_path)

for patient in list_nifti_labels:
    nifti_file = nib.load(patient)
    fdata = nifti_file.get_fdata() # retrieves the image data as a NumPy array, here, 64 slides
    np_unique = np.unique(fdata) # Find the unique value in array 
    if len(np_unique) == 1: # if only 0 in the array --> empty image
        print(patient)

C:/Users/User/Downloads/Liver/nifit_files/labels\liver_2_0.nii.gz
C:/Users/User/Downloads/Liver/nifit_files/labels\liver_2_1.nii.gz
C:/Users/User/Downloads/Liver/nifit_files/labels\liver_2_2.nii.gz
C:/Users/User/Downloads/Liver/nifit_files/labels\liver_2_3.nii.gz
C:/Users/User/Downloads/Liver/nifit_files/labels\liver_2_4.nii.gz
C:/Users/User/Downloads/Liver/nifit_files/labels\liver_3_0.nii.gz
C:/Users/User/Downloads/Liver/nifit_files/labels\liver_3_1.nii.gz
C:/Users/User/Downloads/Liver/nifit_files/labels\liver_3_2.nii.gz
C:/Users/User/Downloads/Liver/nifit_files/labels\liver_3_3.nii.gz
C:/Users/User/Downloads/Liver/nifit_files/labels\liver_4_0.nii.gz
C:/Users/User/Downloads/Liver/nifit_files/labels\liver_4_1.nii.gz
C:/Users/User/Downloads/Liver/nifit_files/labels\liver_4_10.nii.gz
C:/Users/User/Downloads/Liver/nifit_files/labels\liver_4_11.nii.gz
C:/Users/User/Downloads/Liver/nifit_files/labels\liver_4_12.nii.gz
C:/Users/User/Downloads/Liver/nifit_files/labels\liver_4_2.nii.gz
C:/User

In [57]:
# Deleting empty images, labels
input_nifti_file_path = 'C:/Users/User/Downloads/Liver/nifit_files/labels/*'
list_nifti_labels = glob(input_nifti_file_path)

input_nifti_image_path = 'C:/Users/User/Downloads/Liver/nifit_files/images/'

for patient in list_nifti_labels:
    nifti_file = nib.load(patient)
    fdata = nifti_file.get_fdata() # retrieves the image data as a NumPy array, here, 64 slides
    np_unique = np.unique(fdata) # Find the unique value in array 
    if len(np_unique) == 1: # if only 0 in the array --> empty image
        # If the NIfTI file has only one unique value, delete it.
        os.remove(patient)
        print(f"Deleted NIfTI file label: {patient}")
        
        # And delete it's corresponding image file
        image_name = os.path.basename(patient)
        os.remove(os.path.join(input_nifti_image_path, image_name))
        print(f"Deleted corresponding image: {os.path.join(input_nifti_image_path, image_name)}")
        

Deleted NIfTI file label: C:/Users/User/Downloads/Liver/nifit_files/labels\liver_2_0.nii.gz
Deleted corresponding image: C:/Users/User/Downloads/Liver/nifit_files/images/liver_2_0.nii.gz
Deleted NIfTI file label: C:/Users/User/Downloads/Liver/nifit_files/labels\liver_2_1.nii.gz
Deleted corresponding image: C:/Users/User/Downloads/Liver/nifit_files/images/liver_2_1.nii.gz
Deleted NIfTI file label: C:/Users/User/Downloads/Liver/nifit_files/labels\liver_2_2.nii.gz
Deleted corresponding image: C:/Users/User/Downloads/Liver/nifit_files/images/liver_2_2.nii.gz
Deleted NIfTI file label: C:/Users/User/Downloads/Liver/nifit_files/labels\liver_2_3.nii.gz
Deleted corresponding image: C:/Users/User/Downloads/Liver/nifit_files/images/liver_2_3.nii.gz
Deleted NIfTI file label: C:/Users/User/Downloads/Liver/nifit_files/labels\liver_2_4.nii.gz
Deleted corresponding image: C:/Users/User/Downloads/Liver/nifit_files/images/liver_2_4.nii.gz
Deleted NIfTI file label: C:/Users/User/Downloads/Liver/nifit_fil